### ISSUE TITLE
feat: 自动读取、构建通识经验

### ISSUE THREAD

**Issue by TonyCrane** [ZJU-Turing/TuringPlugins#4]
从文件读取收集表结果，自动构建到通识经验页面中

进一步设想：在页面中增加筛选、搜索等功能

**Comment by bowling233** [comment]
是打算利用腾讯文档、问卷星之类导出的 Excel 表格进行构建嘛😋

**Comment by TonyCrane** [comment]
> 是打算利用腾讯文档、问卷星之类导出的 Excel 表格进行构建嘛😋

确实，我们一直用的同一份腾讯收集表传了三届，然后导出结果我手抄到 markdown 里的，太蠢了（x
